DROP TABLE IF EXISTS product_storage CASCADE;

CREATE TABLE IF NOT EXISTS product_storage (
    product_id UUID NOT NULL UNIQUE PRIMARY KEY,

    fragile BOOLEAN,

    width DOUBLE PRECISION NOT NULL,
    height DOUBLE PRECISION NOT NULL,
    depth DOUBLE PRECISION NOT NULL,

    weight DOUBLE PRECISION NOT NULL,
    quantity BIGINT NOT NULL DEFAULT 0
);